[package]
name = "shadown-runner"
version = "0.1.0"
edition = "2021"

[features]
debug = ["bevy_rapier2d/debug-render-2d"]

[dependencies]
bevy = "0.15"
bevy_rapier2d = "0.29"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
